/* mapInfo.c was originally generated by the autoSql program, which also 
 * generated mapInfo.h and mapInfo.sql.  This module links the database and
 * the RAM representation of objects. */

#include "common.h"
#include "linefile.h"
#include "dystring.h"
#include "jksql.h"
#include "mapInfo.h"

static char const rcsid[] = "$Id:$";

/* definitions for chainSubset column */
static char *values_chainSubset[] = {"unknown", "all", "syn", "rbest", NULL};
static struct hash *valhash_chainSubset = NULL;

void mapInfoStaticLoad(char **row, struct mapInfo *ret)
/* Load a row from mapInfo table into ret.  The contents of ret will
 * be replaced at the next call to this function. */
{

ret->srcQName = row[0];
ret->srcQStart = sqlSigned(row[1]);
ret->srcQEnd = sqlSigned(row[2]);
ret->srcQSize = sqlSigned(row[3]);
ret->srcTName = row[4];
ret->srcTStart = sqlSigned(row[5]);
ret->srcTEnd = sqlSigned(row[6]);
ret->srcStrand = row[7][0];
ret->srcAligned = sqlSigned(row[8]);
ret->mappingQName = row[9];
ret->mappingQStart = sqlSigned(row[10]);
ret->mappingQEnd = sqlSigned(row[11]);
ret->mappingTName = row[12];
ret->mappingTStart = sqlSigned(row[13]);
ret->mappingTEnd = sqlSigned(row[14]);
ret->mappingStrand = row[15][0];
ret->mappingId = row[16];
ret->mappedQName = row[17];
ret->mappedQStart = sqlSigned(row[18]);
ret->mappedQEnd = sqlSigned(row[19]);
ret->mappedTName = row[20];
ret->mappedTStart = sqlSigned(row[21]);
ret->mappedTEnd = sqlSigned(row[22]);
ret->mappedStrand = row[23][0];
ret->mappedAligned = sqlSigned(row[24]);
ret->qStartTrunc = sqlSigned(row[25]);
ret->qEndTrunc = sqlSigned(row[26]);
ret->chainSubset = sqlEnumParse(row[27], values_chainSubset, &valhash_chainSubset);
}

struct mapInfo *mapInfoLoad(char **row)
/* Load a mapInfo from row fetched with select * from mapInfo
 * from database.  Dispose of this with mapInfoFree(). */
{
struct mapInfo *ret;

AllocVar(ret);
ret->srcQName = cloneString(row[0]);
ret->srcQStart = sqlSigned(row[1]);
ret->srcQEnd = sqlSigned(row[2]);
ret->srcQSize = sqlSigned(row[3]);
ret->srcTName = cloneString(row[4]);
ret->srcTStart = sqlSigned(row[5]);
ret->srcTEnd = sqlSigned(row[6]);
ret->srcStrand = row[7][0];
ret->srcAligned = sqlSigned(row[8]);
ret->mappingQName = cloneString(row[9]);
ret->mappingQStart = sqlSigned(row[10]);
ret->mappingQEnd = sqlSigned(row[11]);
ret->mappingTName = cloneString(row[12]);
ret->mappingTStart = sqlSigned(row[13]);
ret->mappingTEnd = sqlSigned(row[14]);
ret->mappingStrand = row[15][0];
ret->mappingId = cloneString(row[16]);
ret->mappedQName = cloneString(row[17]);
ret->mappedQStart = sqlSigned(row[18]);
ret->mappedQEnd = sqlSigned(row[19]);
ret->mappedTName = cloneString(row[20]);
ret->mappedTStart = sqlSigned(row[21]);
ret->mappedTEnd = sqlSigned(row[22]);
ret->mappedStrand = row[23][0];
ret->mappedAligned = sqlSigned(row[24]);
ret->qStartTrunc = sqlSigned(row[25]);
ret->qEndTrunc = sqlSigned(row[26]);
ret->chainSubset = sqlEnumParse(row[27], values_chainSubset, &valhash_chainSubset);
return ret;
}

struct mapInfo *mapInfoLoadAll(char *fileName) 
/* Load all mapInfo from a whitespace-separated file.
 * Dispose of this with mapInfoFreeList(). */
{
struct mapInfo *list = NULL, *el;
struct lineFile *lf = lineFileOpen(fileName, TRUE);
char *row[28];

while (lineFileRow(lf, row))
    {
    el = mapInfoLoad(row);
    slAddHead(&list, el);
    }
lineFileClose(&lf);
slReverse(&list);
return list;
}

struct mapInfo *mapInfoLoadAllByChar(char *fileName, char chopper) 
/* Load all mapInfo from a chopper separated file.
 * Dispose of this with mapInfoFreeList(). */
{
struct mapInfo *list = NULL, *el;
struct lineFile *lf = lineFileOpen(fileName, TRUE);
char *row[28];

while (lineFileNextCharRow(lf, chopper, row, ArraySize(row)))
    {
    el = mapInfoLoad(row);
    slAddHead(&list, el);
    }
lineFileClose(&lf);
slReverse(&list);
return list;
}

struct mapInfo *mapInfoCommaIn(char **pS, struct mapInfo *ret)
/* Create a mapInfo out of a comma separated string. 
 * This will fill in ret if non-null, otherwise will
 * return a new mapInfo */
{
char *s = *pS;

if (ret == NULL)
    AllocVar(ret);
ret->srcQName = sqlStringComma(&s);
ret->srcQStart = sqlSignedComma(&s);
ret->srcQEnd = sqlSignedComma(&s);
ret->srcQSize = sqlSignedComma(&s);
ret->srcTName = sqlStringComma(&s);
ret->srcTStart = sqlSignedComma(&s);
ret->srcTEnd = sqlSignedComma(&s);
sqlFixedStringComma(&s, &(ret->srcStrand), sizeof(ret->srcStrand));
ret->srcAligned = sqlSignedComma(&s);
ret->mappingQName = sqlStringComma(&s);
ret->mappingQStart = sqlSignedComma(&s);
ret->mappingQEnd = sqlSignedComma(&s);
ret->mappingTName = sqlStringComma(&s);
ret->mappingTStart = sqlSignedComma(&s);
ret->mappingTEnd = sqlSignedComma(&s);
sqlFixedStringComma(&s, &(ret->mappingStrand), sizeof(ret->mappingStrand));
ret->mappingId = sqlStringComma(&s);
ret->mappedQName = sqlStringComma(&s);
ret->mappedQStart = sqlSignedComma(&s);
ret->mappedQEnd = sqlSignedComma(&s);
ret->mappedTName = sqlStringComma(&s);
ret->mappedTStart = sqlSignedComma(&s);
ret->mappedTEnd = sqlSignedComma(&s);
sqlFixedStringComma(&s, &(ret->mappedStrand), sizeof(ret->mappedStrand));
ret->mappedAligned = sqlSignedComma(&s);
ret->qStartTrunc = sqlSignedComma(&s);
ret->qEndTrunc = sqlSignedComma(&s);
ret->chainSubset = sqlEnumComma(&s, values_chainSubset, &valhash_chainSubset);
*pS = s;
return ret;
}

void mapInfoFree(struct mapInfo **pEl)
/* Free a single dynamically allocated mapInfo such as created
 * with mapInfoLoad(). */
{
struct mapInfo *el;

if ((el = *pEl) == NULL) return;
freeMem(el->srcQName);
freeMem(el->srcTName);
freeMem(el->mappingQName);
freeMem(el->mappingTName);
freeMem(el->mappingId);
freeMem(el->mappedQName);
freeMem(el->mappedTName);
freez(pEl);
}

void mapInfoFreeList(struct mapInfo **pList)
/* Free a list of dynamically allocated mapInfo's */
{
struct mapInfo *el, *next;

for (el = *pList; el != NULL; el = next)
    {
    next = el->next;
    mapInfoFree(&el);
    }
*pList = NULL;
}

void mapInfoOutput(struct mapInfo *el, FILE *f, char sep, char lastSep) 
/* Print out mapInfo.  Separate fields with sep. Follow last field with lastSep. */
{
if (sep == ',') fputc('"',f);
fprintf(f, "%s", el->srcQName);
if (sep == ',') fputc('"',f);
fputc(sep,f);
fprintf(f, "%d", el->srcQStart);
fputc(sep,f);
fprintf(f, "%d", el->srcQEnd);
fputc(sep,f);
fprintf(f, "%d", el->srcQSize);
fputc(sep,f);
if (sep == ',') fputc('"',f);
fprintf(f, "%s", el->srcTName);
if (sep == ',') fputc('"',f);
fputc(sep,f);
fprintf(f, "%d", el->srcTStart);
fputc(sep,f);
fprintf(f, "%d", el->srcTEnd);
fputc(sep,f);
if (sep == ',') fputc('"',f);
fprintf(f, "%c", el->srcStrand);
if (sep == ',') fputc('"',f);
fputc(sep,f);
fprintf(f, "%d", el->srcAligned);
fputc(sep,f);
if (sep == ',') fputc('"',f);
fprintf(f, "%s", el->mappingQName);
if (sep == ',') fputc('"',f);
fputc(sep,f);
fprintf(f, "%d", el->mappingQStart);
fputc(sep,f);
fprintf(f, "%d", el->mappingQEnd);
fputc(sep,f);
if (sep == ',') fputc('"',f);
fprintf(f, "%s", el->mappingTName);
if (sep == ',') fputc('"',f);
fputc(sep,f);
fprintf(f, "%d", el->mappingTStart);
fputc(sep,f);
fprintf(f, "%d", el->mappingTEnd);
fputc(sep,f);
if (sep == ',') fputc('"',f);
fprintf(f, "%c", el->mappingStrand);
if (sep == ',') fputc('"',f);
fputc(sep,f);
if (sep == ',') fputc('"',f);
fprintf(f, "%s", el->mappingId);
if (sep == ',') fputc('"',f);
fputc(sep,f);
if (sep == ',') fputc('"',f);
fprintf(f, "%s", el->mappedQName);
if (sep == ',') fputc('"',f);
fputc(sep,f);
fprintf(f, "%d", el->mappedQStart);
fputc(sep,f);
fprintf(f, "%d", el->mappedQEnd);
fputc(sep,f);
if (sep == ',') fputc('"',f);
fprintf(f, "%s", el->mappedTName);
if (sep == ',') fputc('"',f);
fputc(sep,f);
fprintf(f, "%d", el->mappedTStart);
fputc(sep,f);
fprintf(f, "%d", el->mappedTEnd);
fputc(sep,f);
if (sep == ',') fputc('"',f);
fprintf(f, "%c", el->mappedStrand);
if (sep == ',') fputc('"',f);
fputc(sep,f);
fprintf(f, "%d", el->mappedAligned);
fputc(sep,f);
fprintf(f, "%d", el->qStartTrunc);
fputc(sep,f);
fprintf(f, "%d", el->qEndTrunc);
fputc(sep,f);
if (sep == ',') fputc('"',f);
sqlEnumPrint(f, el->chainSubset, values_chainSubset);
if (sep == ',') fputc('"',f);
fputc(lastSep,f);
}

/* -------------------------------- End autoSql Generated Code -------------------------------- */

