table mapInfo
"psl mapping information" (
    string srcQName;            "srcQName"
    int srcQStart;              "srcQStart"
    int srcQEnd;                "srcQEnd"
    int srcQSize;               "srcQSize"
    string srcTName;            "srcTName"
    int srcTStart;              "srcTStart"
    int srcTEnd;                "srcTEnd"
    string srcStrand;           "srcStrand"
    int srcAligned;             "srcAligned"
    string mappingQName;        "mappingQName"
    int mappingQStart;          "mappingQStart"
    int mappingQEnd;            "mappingQEnd"
    string mappingTName;        "mappingTName"
    int mappingTStart;          "mappingTStart"
    int mappingTEnd;            "mappingTEnd"
    string mappingStrand;       "mappingStrand"
    string mappingId;           "mappingId"
    string mappedQName;         "mappedQName"
    int mappedQStart;           "mappedQStart"
    int mappedQEnd;             "mappedQEnd"
    string mappedTName;         "mappedTName"
    int mappedTStart;           "mappedTStart"
    int mappedTEnd;             "mappedTEnd"
    string mappedStrand;        "mappedStrand"
    int mappedAligned;          "mappedAligned"
    int qStartTrunc;            "qStartTrunc"
    int qEndTrunc;              "qEndTrunc"
)
